version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: f1_store_postgres
    environment:
      POSTGRES_USER: ${postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
        - "5432:5432"
    env_file:
      - .env

  backend_rds:
    build: ./backend_rds
    container_name: f1_store_backend_rds
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - .env

  redis_server:
    image: redis:alpine
    container_name: f1_store_redis
    ports:
      - "6379:6379"
    command: >
      sh -c "redis-server --requirepass \"$${REDIS_PASSWORD}\""
    env_file:
      - .env

  backend_redis:
    build: ./backend_redis
    container_name: f1_store_backend_redis
    depends_on:
      - redis_server
    ports:
      - "8001:8001"
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: f1_store_frontend
    ports:
      - "3000:80"
    env_file:
      - .env