version: "3.9"

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis_server:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: >
      sh -c "redis-server --requirepass \"$${REDIS_PASSWORD}\""
    env_file:
      - .env

  backend_rds:
    image: ivar26/f1-backend-rds
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env


  backend_redis:
    image: ivar26/f1-backend-redis
    ports:
      - "8001:8001"
    depends_on:
      - redis_server
    env_file:
      - .env

  frontend:
    image: ivar26/f1-frontend
    ports:
      - "3000:80"
    env_file:
      - .env
